FUNCTION gwyjb

PARAMETERS tjb

DO case
CASE tjb=="1"
    RETURN "公务员一级"
CASE tjb=="2"
    RETURN "公务员二级"
CASE tjb=="3"
    RETURN "公务员三级"
CASE tjb=="4"
    RETURN "公务员四级"
CASE tjb=="5"
    RETURN "公务员五级"
CASE tjb=="6"
    RETURN "公务员六级"
CASE tjb=="7"
    RETURN "公务员七级"
CASE tjb=="8"
    RETURN "公务员八级"
CASE tjb=="9"
    RETURN "公务员九级"
CASE tjb=="10"
    RETURN "公务员十级"
CASE tjb=="11"
    RETURN "公务员十一级"
CASE tjb=="12"
    RETURN "公务员十二级"
CASE tjb=="13"
    RETURN "公务员十三级"
CASE tjb=="14"
    RETURN "公务员十四级"
CASE tjb=="15"
    RETURN "公务员十五级"
CASE tjb=="16"
    RETURN "公务员十六级"
CASE tjb=="17"
    RETURN "公务员十七级"
CASE tjb=="18"
    RETURN "公务员十八级  "
CASE tjb=="19"
    RETURN "公务员十九级  "
CASE tjb=="20"
    RETURN "公务员二十级  "
CASE tjb=="21"
    RETURN "公务员二十一级"
CASE tjb=="22"
    RETURN "公务员二十二级"
CASE tjb=="23"
    RETURN "公务员二十三级"
CASE tjb=="24"
    RETURN "公务员二十四级"
CASE tjb=="25"
    RETURN "公务员二十五级"
CASE tjb=="26"
    RETURN "公务员二十六级"
CASE tjb=="27"
    RETURN "公务员二十七级"
OTHERWISE
    RETURN "              "
ENDCASE
