FUNCTION gzdy

PARAMETERS tczwbm,tcxl

LOCAL tgzdy

DO case
CASE tczwbm='0130'
	tgzdy="省部级正职                        "
CASE tczwbm='0140'
	tgzdy="省部级副职                        "
CASE tczwbm='0150'
	tgzdy="厅局级正职                        "
CASE tczwbm='0160'
	tgzdy="厅局级副职                        "
CASE tczwbm='0170'
	tgzdy="县处级正职                        "
CASE tczwbm='0180'
	tgzdy="县处级副职                        "
CASE tczwbm='0190'
	tgzdy="乡科级正职                        "
CASE tczwbm='01A0'
	tgzdy="乡科级副职                        "
CASE tczwbm='01B0'
	tgzdy="一级科员及相当层次职级            "
CASE tczwbm='01C0'
	tgzdy="二级科员及相当层次职级            "
CASE tczwbm='2301'
	tgzdy="一级巡视员及相当层次职级          "
CASE tczwbm='2302'
	tgzdy="二级巡视员及相当层次职级          "
CASE tczwbm='2303'
	tgzdy="一级调研员及相当层次职级          "
CASE tczwbm='2304'
	tgzdy="二级调研员及相当层次职级          "
CASE tczwbm='2305'
	tgzdy="三级调研员及相当层次职级          "
CASE tczwbm='2306'
	tgzdy="四级调研员及相当层次职级          "
CASE tczwbm='2307'
	tgzdy="一级主任科员及相当层次职级        "
CASE tczwbm='2308'
	tgzdy="二级主任科员及相当层次职级        "
CASE tczwbm='2309'
	tgzdy="三级主任科员及相当层次职级        "
CASE tczwbm='2310'
	tgzdy="四级主任科员及相当层次职级        "
CASE tczwbm='2311'
	tgzdy="一级科员及相当层次职级            "
CASE tczwbm='2312'
	tgzdy="二级科员及相当层次职级            "
CASE tczwbm='2201'
	tgzdy="警务技术一级总监                  "
CASE tczwbm='2202'
	tgzdy="警务技术二级总监                  "
CASE tczwbm='2203'
	tgzdy="警务技术一级主任                  "
CASE tczwbm='2204'
	tgzdy="警务技术二级主任                  "
CASE tczwbm='2205'
	tgzdy="警务技术三级主任                  "
CASE tczwbm='2206'
	tgzdy="警务技术四级主任                  "
CASE tczwbm='2207'
	tgzdy="警务技术一级主管                  "
CASE tczwbm='2208'
	tgzdy="警务技术二级主管                  "
CASE tczwbm='2209'
	tgzdy="警务技术三级主管                  "
CASE tczwbm='2210'
	tgzdy="警务技术四级主管                  "
CASE tczwbm='2211'
	tgzdy="警务技术员                        "
CASE tczwbm='2101'
	tgzdy="一级警务专员                      "
CASE tczwbm='2102'
	tgzdy="二级警务专员                      "
CASE tczwbm='2103'
	tgzdy="一级高级警长                      "
CASE tczwbm='2104'
	tgzdy="二级高级警长                      "
CASE tczwbm='2105'
	tgzdy="三级高级警长                      "
CASE tczwbm='2106'
	tgzdy="四级高级警长                      "
CASE tczwbm='2107'
	tgzdy="一级警长                          "
CASE tczwbm='2108'
	tgzdy="二级警长                          "
CASE tczwbm='2109'
	tgzdy="三级警长                          "
CASE tczwbm='2110'
	tgzdy="四级警长                          "
CASE tczwbm='2111'
	tgzdy="一级警员                          "
CASE tczwbm='2112'
	tgzdy="二级警员                          "
CASE tczwbm='2401'
	tgzdy="（执法）一级巡视员及相当层次职级  "
CASE tczwbm='2402'
	tgzdy="（执法）二级巡视员及相当层次职级  "
CASE tczwbm='2403'
	tgzdy="（执法）一级调研员及相当层次职级  "
CASE tczwbm='2404'
	tgzdy="（执法）二级调研员及相当层次职级  "
CASE tczwbm='2405'
	tgzdy="（执法）三级调研员及相当层次职级  "
CASE tczwbm='2406'
	tgzdy="（执法）四级调研员及相当层次职级  "
CASE tczwbm='2407'
	tgzdy="（执法）一级主任科员及相当层次职级"
CASE tczwbm='2408'
	tgzdy="（执法）二级主任科员及相当层次职级"
CASE tczwbm='2409'
	tgzdy="（执法）三级主任科员及相当层次职级"
CASE tczwbm='2410'
	tgzdy="（执法）四级主任科员及相当层次职级"
CASE tczwbm='2411'
	tgzdy="（执法）一级科员及相当层次职级    "
CASE tczwbm='2412'
	tgzdy="（执法）二级科员及相当层次职级    "
CASE tczwbm='2501'
	tgzdy="（专技）一级巡视员及相当层次职级  "
CASE tczwbm='2502'
	tgzdy="（专技）二级巡视员及相当层次职级  "
CASE tczwbm='2503'
	tgzdy="（专技）一级调研员及相当层次职级  "
CASE tczwbm='2504'
	tgzdy="（专技）二级调研员及相当层次职级  "
CASE tczwbm='2505'
	tgzdy="（专技）三级调研员及相当层次职级  "
CASE tczwbm='2506'
	tgzdy="（专技）四级调研员及相当层次职级  "
CASE tczwbm='2507'
	tgzdy="（专技）一级主任科员及相当层次职级"
CASE tczwbm='2508'
	tgzdy="（专技）二级主任科员及相当层次职级"
CASE tczwbm='2509'
	tgzdy="（专技）三级主任科员及相当层次职级"
CASE tczwbm='2510'
	tgzdy="（专技）四级主任科员及相当层次职级"
CASE tczwbm='2511'
	tgzdy="（专技）一级科员及相当层次职级    "
CASE tczwbm='2512'
	tgzdy="（专技）二级科员及相当层次职级    "
CASE tczwbm='2602'
	tgzdy="二级巡视员及相当层次职级          "
CASE tczwbm='2603'
	tgzdy="一级调研员及相当层次职级          "
CASE tczwbm='2604'
	tgzdy="二级调研员及相当层次职级          "
CASE tczwbm='2605'
	tgzdy="三级调研员及相当层次职级          "
CASE tczwbm='2606'
	tgzdy="四级调研员及相当层次职级          "
CASE tczwbm='2607'
	tgzdy="一级主任科员及相当层次职级        "
CASE tczwbm='2608'
	tgzdy="二级主任科员及相当层次职级        "
CASE tczwbm='2609'
	tgzdy="三级主任科员及相当层次职级        "
CASE tczwbm='2610'
	tgzdy="四级主任科员及相当层次职级        "
CASE tczwbm='2611'
	tgzdy="一级科员及相当层次职级            "
CASE tczwbm='2702'
	tgzdy="二级巡视员及相当层次职级          "
CASE tczwbm='2703'
	tgzdy="一级调研员及相当层次职级          "
CASE tczwbm='2704'
	tgzdy="二级调研员及相当层次职级          "
CASE tczwbm='2705'
	tgzdy="三级调研员及相当层次职级          "
CASE tczwbm='2706'
	tgzdy="四级调研员及相当层次职级          "
CASE tczwbm='2707'
	tgzdy="一级主任科员及相当层次职级        "
CASE tczwbm='2708'
	tgzdy="二级主任科员及相当层次职级        "
CASE tczwbm='2709'
	tgzdy="三级主任科员及相当层次职级        "
CASE tczwbm='2710'
	tgzdy="四级主任科员及相当层次职级        "
CASE tczwbm='2711'
	tgzdy="一级科员及相当层次职级            "
CASE tczwbm='2803'
	tgzdy="一级调研员及相当层次职级          "
CASE tczwbm='2804'
	tgzdy="二级调研员及相当层次职级          "
CASE tczwbm='2805'
	tgzdy="三级调研员及相当层次职级          "
CASE tczwbm='2806'
	tgzdy="四级调研员及相当层次职级          "
CASE tczwbm='2807'
	tgzdy="一级主任科员及相当层次职级        "
CASE tczwbm='2808'
	tgzdy="二级主任科员及相当层次职级        "
CASE tczwbm='2809'
	tgzdy="三级主任科员及相当层次职级        "
CASE tczwbm='2810'
	tgzdy="四级主任科员及相当层次职级        "
CASE tczwbm='2811'
	tgzdy="一级科员及相当层次职级            "
CASE tczwbm='2812'
	tgzdy="二级科员及相当层次职级            "

CASE tczwbm="01A1"
    tgzdy="四级主任科员及相当层次职级       "
CASE tczwbm="0191"
    tgzdy="二级主任科员及相当层次职级       "
CASE tczwbm="0181"
    tgzdy="四级调研员及相当层次职级         "
CASE tczwbm="0171"
    tgzdy="二级调研员及相当层次职级         "
CASE tczwbm="0161"
    tgzdy="二级巡视员及相当层次职级         "
CASE tczwbm="0151"
    tgzdy="一级巡视员及相当层次职级         "

CASE tczwbm="1004"
    tgzdy="专技四级        "
CASE tczwbm="1005"
    tgzdy="专技五级        "
CASE tczwbm="1006"
    tgzdy="专技六级        "
CASE tczwbm="1007"
    tgzdy="专技七级        "
CASE tczwbm="1008"
    tgzdy="专技八级        "
CASE tczwbm="1009"
    tgzdy="专技九级        "
CASE tczwbm="1010"
    tgzdy="专技十级        "
CASE tczwbm="1011"
    tgzdy="专技十一级      "
CASE tczwbm="1012"
    tgzdy="专技十二级      "
CASE tczwbm="1013"
    tgzdy="专技十三级      "

CASE tczwbm="0801"
    tgzdy="技工一级        "
CASE tczwbm="0802"
    tgzdy="技工二级        "
CASE tczwbm="0803"
    tgzdy="技工三级        "
CASE tczwbm="0804"
    tgzdy="技工四级        "
CASE tczwbm="0805"
    tgzdy="技工五级        "
CASE tczwbm="0901"
    tgzdy="普工      "

CASE tczwbm="0705"
    tgzdy="职员三级        "
CASE tczwbm="0706"
    tgzdy="职员四级        "
CASE tczwbm="0707"
    tgzdy="职员五级        "
CASE tczwbm="0708"
    tgzdy="职员六级        "
CASE tczwbm="0709"
    tgzdy="职员七级        "
CASE tczwbm="070A"
    tgzdy="职员八级        "
CASE tczwbm="070B"
    tgzdy="职员九级        "
CASE tczwbm="070C"
    tgzdy="职员十级        "

CASE tczwbm="0715"
    tgzdy="职员等级三级    "
CASE tczwbm="0716"
    tgzdy="职员等级四级    "
CASE tczwbm="0717"
    tgzdy="职员等级五级    "
CASE tczwbm="0718"
    tgzdy="职员等级六级    "
CASE tczwbm="0719"
    tgzdy="职员等级七级    "
CASE tczwbm="071A"
    tgzdy="职员等级八级    "
CASE tczwbm="071B"
    tgzdy="职员等级九级    "
CASE tczwbm="071C"
    tgzdy="职员等级十级    "

CASE (LEFT(tczwbm,2)="08" OR LEFT(tczwbm,2)="08") AND AT('F',tczwbm)>0
    tgzdy="工勤见习期      "

CASE AT('F',tczwbm)>0 AND INLIST(LEFT(tczwbm,2),'07','10','11')
    tgzdy = IIF(AT('博士',tcxl)>0,'博士初期        ',IIF(AT('硕士',tcxl)>0,'硕士初期        ',IIF(AT('本科',tcxl)>0,'本科见习期      ',IIF(AT('专科',tcxl)>0,'专科见习期      ','高中、中专见习期'))))

CASE AT('F',tczwbm)>0 AND !INLIST(LEFT(tczwbm,2),'07','10','11')
    tgzdy = "                                "

OTHERWISE 
	SELECT DISTINCT mc from dmb WHERE bm='051'+tczwbm INTO ARRAY lazjcc

	IF _tally>0
	    tgzdy=PADR(lazjcc[1],26,' ')
	ELSE
	    tgzdy=SPACE(26)
	ENDIF
ENDCASE

RETURN tgzdy