FUNCTION xrzwcc
PARAMETERS tczwbm

DO CASE
CASE tczwbm="0150"
    RETURN "厅局级正职    "
CASE tczwbm="0160"
    RETURN "厅局级副职    "
CASE tczwbm="0170"
    RETURN "县处级正职    "
CASE tczwbm="0180"
    RETURN "县处级副职    "
CASE tczwbm="0190"
    RETURN "乡科级正职    "
CASE tczwbm="01A0"
    RETURN "乡科级副职    "
CASE AT("F",tczwbm)>0
    RETURN "试用期人员    "

CASE tczwbm="0315"
    RETURN "一级高级法官  "
CASE tczwbm="0316"
    RETURN "二级高级法官  "
CASE tczwbm="0317"
    RETURN "三级高级法官  "
CASE tczwbm="0318"
    RETURN "四级高级法官  "
CASE tczwbm="0319"
    RETURN "一级法官      "
CASE tczwbm="031A"
    RETURN "二级法官      "
CASE tczwbm="031B"
    RETURN "三级法官      "
CASE tczwbm="031C"
    RETURN "四级法官      "
CASE tczwbm="031D"
    RETURN "五级法官      "

CASE tczwbm="0325"
    RETURN "一级高级检察官"
CASE tczwbm="0326"
    RETURN "二级高级检察官"
CASE tczwbm="0327"
    RETURN "三级高级检察官"
CASE tczwbm="0328"
    RETURN "四级高级检察官"
CASE tczwbm="0329"
    RETURN "一级检察官    "
CASE tczwbm="032A"
    RETURN "二级检察官    "
CASE tczwbm="032B"
    RETURN "三级检察官    "
CASE tczwbm="032C"
    RETURN "四级检察官    "
CASE tczwbm="032D"
    RETURN "五级检察官    "

OTHERWISE 
    RETURN "              "
ENDCASE